blank_issues_enabled: false
contact_links:
  - name: V2Ray Procedural issues
    url: https://github.com/v2fly/v2ray-core/
    about: If you have a question about V2Ray instead of v2rayNG, please go to this link to discuss.