name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.MY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare
        run: |
          sudo apt-get -y install dos2unix apksigner

      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Clone
        run: |
          git clone https://Blawuken:$GH_TOKEN@github.com/Blawuken/v2rayNG

      - name: Build
        run: |
          cd ${{ github.workspace }}/v2rayNG
          dos2unix ./gradlew
          ./gradlew assemble

      - name: Sign APK
        run: |
          cd ${{ github.workspace }}/v2rayNG
          apksigner sign --key platform.pk8 --cert platform.x509.pem app/build/outputs/apk/release/*arm64-v8a.apk
          apksigner sign --key platform.pk8 --cert platform.x509.pem app/build/outputs/apk/release/*armeabi-v7a.apk
          apksigner sign --key platform.pk8 --cert platform.x509.pem app/build/outputs/apk/release/*x86.apk
          apksigner sign --key platform.pk8 --cert platform.x509.pem app/build/outputs/apk/release/*x86_64.apk
          apksigner sign --key platform.pk8 --cert platform.x509.pem app/build/outputs/apk/release/*universal.apk

      - name: Release
        uses: softprops/action-gh-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repository: Blawuken/Neko_v2rayNG
          body_path: ${{ github.workspace }}/CHANGELOG.txt
          token: ${{ secrets.MY_TOKEN }}
          files: |
            ${{ github.workspace }}/v2rayNG/app/build/outputs/apk/release/*arm64-v8a.apk
            ${{ github.workspace }}/v2rayNG/app/build/outputs/apk/release/*armeabi-v7a.apk
            ${{ github.workspace }}/v2rayNG/app/build/outputs/apk/release/*x86.apk
            ${{ github.workspace }}/v2rayNG/app/build/outputs/apk/release/*x86_64.apk
            ${{ github.workspace }}/v2rayNG/app/build/outputs/apk/release/*universal.apk
